openapi: 3.0.3
info:
  title: Task Manager API
  description: Simple example API for tasks for current project.
  version: "1.0.0"
servers:
  - url: https://api.example.com/v1
paths:
  /tasks:
    get:
      summary: List tasks
      responses:
        '200':
          description: A JSON array of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Created
  /tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get task by id
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Not found
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        completed:
          type: boolean
      required: [id, title]
    TaskInput:
      type: object
      properties:
        title:
          type: string
        completed:
          type: boolean
      required: [title]

